### ISSUE TITLE
用起来过一次，NodeJS需要更新，但后面还是出问题了

### ISSUE THREAD

**Issue by dream10201** [Bitmoe/PortableHexo#5]
`$ hexo d
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 7, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object.exports.prettifyError (E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\lib.js:34:15)
    at E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\environment.js:486:31
    at new_cls.root [as rootRenderFunc] (eval at _compile (E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\environment.js:565:24), <anonymous>:161:3)
    at new_cls.render (E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\environment.js:479:15)
    at Hexo.module.exports (E:\OneDrive\MyBlog-64bit\blog\node_modules\hexo-generator-feed\lib\generator.js:28:22)
    at Hexo.tryCatcher (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\method.js:15:34)
    at E:\OneDrive\MyBlog-64bit\blog\node_modules\hexo\lib\hexo\index.js:337:24
    at tryCatcher (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\promise_array.js:113:31)
    at MappingPromiseArray.init (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
FATAL (unknown path) [Line 7, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
Template render error: (unknown path) [Line 7, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object.exports.prettifyError (E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\lib.js:34:15)
    at E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\environment.js:486:31
    at new_cls.root [as rootRenderFunc] (eval at _compile (E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\environment.js:565:24), <anonymous>:161:3)
    at new_cls.render (E:\OneDrive\MyBlog-64bit\blog\node_modules\nunjucks\src\environment.js:479:15)
    at Hexo.module.exports (E:\OneDrive\MyBlog-64bit\blog\node_modules\hexo-generator-feed\lib\generator.js:28:22)
    at Hexo.tryCatcher (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\method.js:15:34)
    at E:\OneDrive\MyBlog-64bit\blog\node_modules\hexo\lib\hexo\index.js:337:24
    at tryCatcher (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\promise_array.js:113:31)
    at MappingPromiseArray.init (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\OneDrive\MyBlog-64bit\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
`

**Comment by ghw** [comment]
您好，方便加一下群嘛？QQ群335919529
